sudo: required
services:
  - docker

before_install:
  - docker build -t swmn/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true swmn/react-test npm test

after_success:
  - docker build -t swmn/multi-client ./client
  - docker build -t swmn/multi-nginx ./nginx
  - docker build -t swmn/multi-server ./server
  - docker build -t swmn/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push swmn/multi-client
  - docker push swmn/multi-nginx
  - docker push swmn/multi-server
  - docker push swmn/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-northeast-1a
  app: multi-docker
  env: Multi-docker-otake-v1-env
  bucket_name: elasticbeanstalk-ap-northeast-1-085107194442
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY